version: '3.7'
services:
  tests:
    build:
      context: tests/
    networks:
      - tests_network

  nginx:
    image: nginx:1.17.9
    ports:
      - 8082:8080
    networks:
      - tests_network

networks:
  tests_network:
    driver: bridge